on: [push, pull_request]

name: Continuous integration

jobs:
  build:
    name: Test ${{ matrix.job.target }}
    runs-on: ${{ matrix.job.os }}
    strategy:
      fail-fast: false
      matrix:
        job:
          - { target: x86_64-unknown-linux-gnu, os: ubuntu-20.04 }
          - { target: x86_64-apple-darwin, os: macos-latest }
          - { target: x86_64-pc-windows-msvc, os: windows-latest }

          - { target: aarch64-unknown-linux-gnu, os: ubuntu-20.04, use-cross: true }
    env:
      BUILD_CMD: cargo
      SUBCOMMAND: test

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@1.65.0
      with:
        targets: ${{ matrix.job.target }}

    - name: Install cross
      if: matrix.job.use-cross
      uses: taiki-e/install-action@v2
      with:
        tool: cross@0.2.5

    - name: Overwrite build command env variable
      if: matrix.job.use-cross
      shell: bash
      run: echo "BUILD_CMD=cross" >> $GITHUB_ENV

    - name: Test
      shell: bash
      run: $BUILD_CMD $SUBCOMMAND --target ${{ matrix.job.target }}

  fmt:
    name: Rustfmt
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@1.65.0
      - run: cargo fmt --all -- --check

  actionlint:
    name: Actionlint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: raven-actions/actionlint@v1
        with:
          shellcheck: false
